Fix errorprone build after SDK ext 22
SDK extensions version 22 introduced
isAutoJoinInAdvancedProtectionModeEnabled, and now errorprone breaks
because of

  [...]/StandardWifiEntry.java:629: \
       Error: Call requires API level CUR_DEVELOPMENT/10000 (current min is 31): \
       android.net.wifi.WifiConfiguration#isAutoJoinInAdvancedProtectionModeEnabled [NewApi]

This is a false positive, and the access to
isAutoJoinInAdvancedProtectionModeEnabled is correctly flag checked. Add
@SuppressLint to unblock the API finalization.

Bug: 481594013
Test: lunch sdk-trunk_staging-userdebug && m out/soong/.intermediates/frameworks/opt/net/wifi/libs/WifiTrackerLib/SdkWifiTrackerLib/android_common/lint/lint-baseline.xml out/soong/.intermediates/frameworks/opt/net/wifi/libs/WifiTrackerLib/SdkWifiTrackerLib/android_common/lint/lint-report.html out/soong/.intermediates/frameworks/opt/net/wifi/libs/WifiTrackerLib/SdkWifiTrackerLib/android_common/lint/lint-report.txt out/soong/.intermediates/frameworks/opt/net/wifi/libs/WifiTrackerLib/SdkWifiTrackerLib/android_common/lint/lint-report.xml out/soong/.intermediates/frameworks/opt/net/wifi/libs/WifiTrackerLib/SdkWifiTrackerLib/android_common/lint/lint-srcs.list out/soong/.intermediates/frameworks/opt/net/wifi/libs/WifiTrackerLib/SdkWifiTrackerLib/android_common/lint/suggested-fixes.zip
Flag: NONE platform SDK finalization
Change-Id: I664d859e4dca87beed4e15069b88ec4dd4c48c2b